name: APM iOS dev Build
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    name: player scraper
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
